### ISSUE TITLE
Question: other app

### ISSUE THREAD

**Issue by Alexey-T** [yazd/DKit#19]
Hi. Good work! Maybe u interested in writing DCD module for my Synwrite?
https://sourceforge.net/p/synwrite/wiki/python%20API/

**Comment by yazd** [comment]
Hello, SynWrite looks like a nice application, but currently I am putting all my free time (which isn't a lot) in my other project, ddbg.
Also, my development is normally on Linux, and it looks like SynWrite doesn't support it natively. Maybe when I get more time and if SynWrite supports Linux a bit more, I will write one.
But thank you for your question.

**Comment by Alexey-T** [comment]
Tks for your answer.I understand that Linux is hard to use in Synw
