### ISSUE TITLE
Building on Windows

### ISSUE THREAD

**Issue by thisdyingsoul** [yazd/DKit#38]
Whe trying to build the server with `dub build --build=release --config=server`
i get this error:

C:\Users\this_\AppData\Roaming\dub\packages\msgpack-d-1.0.0-beta.3\src\msgpack\common.d(14,20): Deprecation: module std.c.windows.winsock is deprecated - Import core.sys.windows.winsock2 instead
src\server\autocomplete.d(233,9): Error: no property 'getParts' for type 'SymbolOwnership'
src\server\autocomplete.d(235,11): Error: no property 'getParts' for type 'DSymbol*'
src\server\autocomplete.d(188,29): Error: function server.autocomplete.symbolSearch no return exp; or assert(0); at end of function
dmd failed with exit code 1.

**Comment by yazd** [comment]
This is a DCD issue, please report it here: https://github.com/Hackerpilot/DCD/
